name: Deploy to Cloud Run

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 'Authenticate to GCP'
        run: |
          echo '${{ secrets.GCP_SA_KEY }}' > ${HOME}/gcp-key.json
          gcloud auth activate-service-account --key-file ${HOME}/gcp-key.json
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
      - name: Build and Deploy
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        run: |
          gcloud builds submit --tag gcr.io/$PROJECT_ID/drunk30-buzz
          gcloud run deploy drunk30-buzz-service \
            --image gcr.io/$PROJECT_ID/drunk30-buzz \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated
